feat: added ratelimits package
sapphire-project/utilities pull request #15
Opened 2020-09-21 11:04 UTC by kyranet

2020-09-21 16:41 UTC, Favna requested changes
- Update the list of files to modify in all-contributors file
- Write actual README

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/CHANGELOG.md
> +# Change Log
Nuke this file, Lerna autogenerates it when needed.

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/README.md
> +\**Deconstruct and generate snowflake IDs using BigInts.*i
`\**` ??
`*i` ??

Also the description is wrong anyway

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/jest.config.js
> +	setupFilesAfterEnv: ['<rootDir>/tests/jest.setup.ts'],
```suggestion
```

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/package.json
> +	"description": "Deconstructs and generates snoflake IDs using BigInts",
Update this

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/package.json
> +	"version": "1.0.1",
```suggestion
	"version": "0.0.1",
```

version will be set to 1.0.0 by lerna

2020-09-21 16:41 UTC, Favna commented on packages/ratelimits/rollup.config.ts
> +			output: { comments: false }
```suggestion
			format: { comments: false }
```

output is from old version of Terser

2020-09-26 12:19 UTC, vladfrangu requested changes

2020-09-26 12:19 UTC, vladfrangu commented on packages/ratelimits/src/lib/Bucket.ts
> +	 * that a 5/5s bucket ({@link BucketLimit#limit Limit} of 5 in 5 seconds
```suggestion
	 * that a 5/5s bucket ({@link BucketLimit#limit limit} of 5 in 5 seconds
```

2020-09-26 19:37 UTC, vladfrangu approved these changes

2020-09-26 20:31 UTC, Favna approved these changes

2020-09-26 20:57 UTC, merged